### ISSUE TITLE
Problem on api login

### ISSUE THREAD

**Issue by xBorja042** [SukiCZ/cardmarket_api#2]
* Cardmakret API v3+ version: 0.1.4
* Python version: 3.9.12
* Operating System: Windows10

I am trying to create an api object as stated on the documentation with:

from cardmarket_api import CardMarketApi

api = CardMarketApi(
    username="username",
    password="password",
    sandbox=True,
)

The problem is that with the credentials I am using I can not get to connect as it says either the username or the password are incorrect but I am pretty sure the credentials are OK: 

An error occurred (NotAuthorizedException) when calling the InitiateAuth operation: Incorrect username or password.

Do I need a specific type of account or am I doing something else wrong? Thanks in advance

**Comment by SukiCZ** [comment]
I'm not sure if you got your hands on their document `Accessing_the_sandbox-updated.docx`
That document describes how to change your initial password and then be able to send a POST request
```sh
curl --location --request POST 'https://cognito-idp.eu-central-1.amazonaws.com/' \
--header 'X-Amz-Target: AWSCognitoIdentityProviderService.InitiateAuth' \
--header 'Content-Type: application/x-amz-json-1.1' \
--data-raw '{
    "ClientId": "15kh0e0f04o1iaq5ie8jf78fuh",
    "AuthFlow": "USER_PASSWORD_AUTH",
    "AuthParameters": {
        "USERNAME": "username",
        "PASSWORD": "password"
    }
}'
```

I have not been granted the permission to share such document (I didn't even asked) but try to reach "Ajda Gruden" on Microsoft Teams. I'm sure she will gladly help you out ☺️ 

Meanwhile, I'll ask for permission to share and maybe start a wiki page.

Hope that helps 🎉

**Comment by xBorja042** [comment]
Thanks a lot for your kindly and friendly explanations. Yes, I was reading on my user account that if I want to use the API I need to ask for permission. From my point of view there shoud exist at least a user to toy around with the API and for doing research purposes before developing something big and serious. I have an idea for a little program but it is just to keep improving Python developing and for watching some prices such as Adeline. Anyway, I will try to reach the contact you have facilitated me! Thanks a lot!

**Comment by SukiCZ** [comment]
hey @xBorja042 just to clarify one thing.
CardMarket currently has a [production API v2](https://api.cardmarket.com/ws/documentation/API_2.0:Main_Page). This client is for version 3 which is Work In Progress from CardMarket perspective (they only support sandbox for now)
If you want to monitor current prices, you should use [this client](https://pypi.org/project/mkmsdk/) for v2 but sure be ready to migrate to v3 later 🙃
